# overrides

spring:
  redis:
    host: localhost
    port: 6379

server:
  servlet:
    context-path: /api

# /api-docs endpoint custom path
springdoc:
  api-docs:
    path: /api-docs

# management
management:
  metrics:
    enabled.jvm: true
    enabled.root: true
    export:
      prometheus:
        enabled: true
  endpoint:
    shutdown.enabled: true
    info.enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.zalando.logbook: TRACE
    org.springframework.security: DEBUG